CFLAGS-libqmap-o := -fPIC
CFLAGS-idm-o := -fPIC
CFLAGS-rec-o := -fPIC
CFLAGS-rec_axis-o := -fPIC
CFLAGS-qmap-o :=
CFLAGS-test-o :=
CFLAGS-test_extended-o :=
CFLAGS-test_multivalue-o :=
CFLAGS-test_record-o :=
CFLAGS-rec_test-o :=
CFLAGS-rec_axis_test-o :=
CFLAGS-rec_axis_bench-o :=
CFLAGS-bench_multivalue-o :=
CFLAGS-bench_rec-o :=
