name: CI Test

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Run shared CI Test Action
        uses: tty-pt/ci/test@main
        with:
          deps: "libqsys,libxxhash-dev"
